application: dost
version: 1
runtime: go
api_version: go1

handlers:
- url: /
  static_files: web/index.html
  upload: web/(.*\.html)
- url: /css
  static_dir: web/css/
- url: /packages
  static_dir: web/packages
- url: /api/.*
  script: _go_app
