name: dost
version: 0.0.1
dependencies:
  angular2: 2.0.0-beta.12
  browser: ^0.10.0
  test: ^0.12.6
  angular2_testing: any
  bootstrap: ^3.3.4
  firebase: ^0.6.5+1
transformers:
- angular2:
   platform_directives:
    - 'package:angular2/common.dart#COMMON_DIRECTIVES'
   platform_pipes:
    - 'package:angular2/common.dart#COMMON_PIPES'
   entry_points: web/main.dart
- bootstrap:
    url: //maxcdn.bootstrapcdn.com/bootstrap/3.3.4
